### ISSUE TITLE
Suite à un import gedcom, je peux dire qui je suis dans l'arbre

### ISSUE THREAD

**Issue by ClementCHA** [paduc/tresor-de-famille#5]
- [x] Créer barre de recherche
- [x] Bouton "c'est moi" => émettre un événement `UserHasDesignatedHimselfAsPerson` (`userId` `personId`)
- [x] Rediriger vers la page personne de la personne selectionnée

![Image](https://user-images.githubusercontent.com/570860/182038792-edb6e1b0-3846-4936-83da-a088426dbbf3.png)

![Image](https://user-images.githubusercontent.com/570860/182038793-9745ea3d-a02f-485e-af9c-b32befb8d341.png)

**Comment by ClementCHA** [comment]
"Bouton "c'est moi" => émettre un événement UserHasDesignatedHimselfAsPerson (userId personId) 

Quand tu mets (userId personId), tu sous entends que les deux existent?

**Comment by paduc** [comment]
Oui voilà, le userId c’est celui de l’utilisateur connecté, et donc accessible dans la session.
La personId c’est l’id de la personne sélectionnée par l’utilisateur.
