### ISSUE TITLE
[Page personne] Je peux ajouter un membre de la famille

### ISSUE THREAD

**Issue by ClementCHA** [paduc/tresor-de-famille#8]
Ceci est nouvelle fonctionnalité qui n'existe pas dans la version `tresor-remix`.

- [ ] Sur la page personne, dans le section appropriée (parents, enfants, époux...), l'utilisateur saisit le nom et click sur le bouton "Ajouter un enfant" (/parent/epoux)
- [ ] Emettre un événement `ChildAdded` (`ParentAdded`/`SpouseAdded`) avec `personId`, `child: { id: string, name: }` (remplacer child par parent, spouse).
- [ ] Mettre à jour la query `getPersonPage.ts` pour inclure ces événements (et donc afficher les nouvelles personnes)

**Comment by ClementCHA** [comment]
Excuse moi de te déranger PA, j'ai merge sur master les branches gedcomImport & gedcomImportSuccess mais en retournant sur ma branche "personPage" ou "addMemberOnPersonPage",  j'ai un :

```
Cannot GET /person/:4b5b7b76-039b-4833-8a47-cfa250bb855c
```


Je comprend pas d'où ça vient, j'ai bien ça sur mon ImportGedcomSuccess.route.ts
```
pageRouter.route('/importGedcomSuccess.html').post(async (request, response) => {
  const { personId } = request.body
  const userId = request.session.id
  console.log('POST on /importGedcomSuccess.html')
  await publish(UserHasDesignatedHimselfAsPerson({ userId, personId }))

  response.redirect(`/person/:${personId}`)
})

```
J'ai bien ma route: 

```
pageRouter.route('/person/:personId').get(requireAuth(), async (request, response) => { ...
... } 
``` 

J'ai mes exports dans les barrel et surtout ça marchait très bien avant les merges sur masters des deux autres branches. 

Any ideas?

**Comment by paduc** [comment]
1) Je ne vois pas ta page dans https://github.com/paduc/tresor-de-famille/tree/master/src/pages

2) Je vois deux commits « Merge master into xxx » qui ne devraient pas être là. Comment as-tu procédé au moment du merge ?

**Comment by ClementCHA** [comment]
Ma page n'est pas là car elle dépend de la branch personPage qui est encore en pull request 

2) J'ai procédé sur les PR de github, résolu les conflits directement depuis github, validé les commits puis merge.

**Comment by ClementCHA** [comment]
Yes,  j'ai tout reboot, upgrade ma version git, update VS Code et l'extension git de vs code. 

Sur master j'ai bien ma branch importGedCom & importGedcomSuccess. 

J'ai bien, sur master la fameuse typo : 
```
response.redirect(`/person/:${personId}'`)
```

Je vais sur ma branch personPage qui est la branche en PR actuellement avec le traitement du gedcom, il n'y a plus la typo: 

```
response.redirect(`/person/:${personId}`)
```

Et pourtant, quand je yarn start sur la branche personPage => 
```
Cannot GET /person/:de21706c-5264-45a7-a01c-f5e3c9a6001e'
```

J'ai beau changer ce redirect, mettre '/' ou n'importe quoi, je reste bloqué sur ce qui semble être master avec ce cannot get /person...

**Comment by paduc** [comment]
On est d’accord que tu dois relancer yarn watch à chaque changement de branche ?

Il est possible que ta compilation ait echoué et que ca soit l’ancien code qui soit situé dans le dossier /dist

**Comment by ClementCHA** [comment]
Oui oui on est d'accord là dessus 😅

En effet, quand je suis sur ma branch "personPage", si je compare les fichiers entre mon src et mon dist, ils sont différents 😒

**Comment by paduc** [comment]
Tu peux vider dist

**Comment by ClementCHA** [comment]
Problème résolu.. 

Excuse moi, ça fait beaucoup de message pour pas grand chose ><

**Comment by paduc** [comment]
Pas de soucis ! Il faut que tu apprennes à t’en sortir un peu seul et pour ça tu as besoin d’aide, c’est normal.
